# Site settings
title: Yggdrassl
description: "Internal Documentation"
baseurl: "" # For GitHub Pages user/organization site keep empty, for project site use /repo-name
url: "https://manugraj-kv.github.io/" # Change to your site URL

# Theme
remote_theme: just-the-docs/just-the-docs

# Color scheme
color_scheme: dark

# Navigation
# Using collections so that sidebar shows folders
collections:
  docs:
    output: true
    permalink: /:collection/:path/
    sort_by: nav_order

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false

# Default settings for all docs
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
      nav_order: 100
      search: true
      has_children: false

# Search
search_enabled: true
search_tokenizer_separator: /[\s/]+/

# Footer
footer_content: ""  # Removes default Just the Docs footer text
last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y"

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at

# Feed settings
feed:
  collections:
    docs:
      path: feed.xml
