# =========================================================
# Site Settings
# =========================================================
title: Yggdrassl
description: "Our tree of knowledge"
url: "https://manugraj-kv.github.io" # Replace with your GitHub Pages URL
baseurl: ""                        # Leave blank unless hosting in subpath

# =========================================================
# Theme
# =========================================================
remote_theme: just-the-docs/just-the-docs

# =========================================================
# Build Settings
# =========================================================
markdown: kramdown
highlighter: rouge

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/

# =========================================================
# Collections
# =========================================================
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# =========================================================
# Defaults
# =========================================================
defaults:
  # Home page
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      nav_order: 1

  # All documents in _docs collection
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: default
      has_children: false
      nav_order: 10
      # Optional: set a default date so "recent docs" works even if not set
      date: 2025-01-01

# =========================================================
# Navigation Links (top right corner)
# =========================================================
aux_links:
  "View on GitHub":
    - "//github.com/manugraj-kv/manugraj-kv.github.io"
aux_links_new_tab: true

color_scheme: dark   # Uncomment for dark mode by default
