site_name: Wandering Docs
site_url: https://<your-username>.github.io/<your-repo>/
repo_url: https://github.com/<your-username>/<your-repo>
repo_name: <your-username>/<your-repo>

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search
  - awesome-pages
  - gen-files:
      scripts:
        - scripts/gen_auto_indexes.py

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - attr_list
  - def_list
  - footnotes
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<your-username>

nav: []  # Let awesome-pages build from the docs/ folder
