site_name: Your Documentation
site_url: https://<your-user>.github.io/<your-repo>/
repo_url: https://github.com/<your-user>/<your-repo>
repo_name: <your-user>/<your-repo>

theme:
  name: material
  features:
    - navigation.instant            # faster page transitions
    - navigation.tracking           # highlight section in sidebar
    - navigation.sections           # nested sections in sidebar
    - navigation.top                # back-to-top button
    - toc.integrate                 # right-side TOC integrates when space allows
    - search.suggest
    - search.highlight
  logo: assets/logo.svg
  favicon: assets/favicon.png

plugins:
  - search                          # full-text search (Lunr)
  - awesome-pages                   # auto nav from folder structure
  - gen-files:
      scripts:
        - scripts/gen_auto_indexes.py  # ensure each folder has an index.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - attr_list
  - def_list
  - footnotes
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<your-user>
nav: []    # intentionally empty; awesome-pages builds it from docs/ tree
