site_name: Your Docs
site_url: https://<your-user>.github.io/<your-repo>/
repo_url: https://github.com/<your-user>/<your-repo>
theme:
  name: material
  features:
    - navigation.instant        # snappy page transitions
    - navigation.tracking       # updates URL on headings
    - navigation.indexes        # folder index pages
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - search:                     # Lunr fallback if Pagefind is disabled
      lang: en
  - awesome-pages               # build nav from folders
  - minify:
      minify_html: true
  - pagefind:                   # primary search index
      indexing_dir: site        # where mkdocs builds
      output_path: site/pagefind
extra:
  generator: false              # removes generator footer/meta
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
nav:                            # optional; omit to let awesome-pages fully drive nav
  - Home: index.md
